name: cicd-cezzis-rag-data-extraction

on:
  pull_request:
    branches: [main]
    paths: [
      data-ingestion/data-extraction-agent/src/**,
      data-ingestion/data-extraction-agent/terraform/**,
      data-ingestion/data-extraction-agent/test/**,
      .github/workflows/cezzis-rag-data-extraction-cicd.yaml
    ]
  push:
    branches: [main]
    paths: [
      data-ingestion/data-extraction-agent/src/**,
      data-ingestion/data-extraction-agent/terraform/**,
      data-ingestion/data-extraction-agent/test/**,
      .github/workflows/cezzis-rag-data-extraction-cicd.yaml
    ]

  workflow_dispatch:

jobs:
  gitVersion:
    name: Git version
    permissions: 
      contents: read
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitVersion.outputs.MajorMinorPatch }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0
      
      - name: Install GetVersion
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: "6.x"

      - name: Use GitVersion
        id: gitVersion
        uses: gittools/actions/gitversion/execute@v4.1.0
        with:
          configFilePath: ./GitVersion.yml

  build:
    name: Build and test
    needs: [gitVersion]
    uses: mtnvencenzo/workflows/.github/workflows/python-build.yaml@main
    with:
      python_version: '3.12'
      working_directory: './data-extraction-agent'
      requirements_file: './requirements.txt'
      requirements_dev_file: './requirements-dev.txt'
      ruff_config: '.ruff.toml'
      pytest_args: '-v'
      upload_artifact: true
      artifact_name: 'cocktails-rag-data-extraction-agent'
      setup_files: '["./Dockerfile-CI"]'
      version: ${{ needs.gitVersion.outputs.semVer }}
    secrets:
      github_packages_pat_token: ${{ secrets.GH_PACKAGES_PAT_TOKEN_READ }}

  docker:
    name: Containerize app
    needs: [build, gitVersion]
    uses: mtnvencenzo/workflows/.github/workflows/docker-build-and-push.yaml@main
    with:
      working_directory: './data-extraction-agent'
      allow_build_and_push: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main' }}
      artifact_name: 'cocktails-rag-data-extraction-agent'
      docker_file_name: 'Dockerfile-CI'
      image_tag: '${{ github.sha }}'
      acr_registry_login_server: 'acrveceusgloshared001.azurecr.io'
      acr_image_repository: 'cocktailsragdataextractionagent'

    secrets:
      acr_registry_login_username: ${{ secrets.ACR_REGISTRY_USERNAME }}
      acr_registry_login_password: ${{ secrets.ACR_REGISTRY_PASSWORD }}

  create_release_prd:
    name: Create release
    if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [docker, gitVersion]
    steps:
      - name: Create release
        uses: mtnvencenzo/workflows/.github/actions/create-release@main
        with:
          version: ${{ needs.gitVersion.outputs.semVer }}